# Generated by Django 5.1.1 on 2024-10-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reportviolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportviolation',
            name='coordinate_x',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportviolation',
            name='coordinate_y',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportviolation',
            name='description2',
            field=models.TextField(blank=True),
        ),
    ]
