@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI5NDMzODIxLCJpYXQiOjE3Mjk0MzAyMjEsImp0aSI6IjgwOWY4NzU3MWZlMzQ3NWI5ZWZlMTkzMDVlOWVmMjZjIiwidXNlcl9pZCI6MX0.4LchpJHBi7t_38hV5SoneVSF-7d9mwrmP1Fky4AIINA


POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{"username":"admin", "password": "1"}

###

GET http://127.0.0.1:8000/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

{}

###

POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNjU3NjkwOCwiaWF0IjoxNzI2NDkwNTA4LCJqdGkiOiI2ZDczMjIzOGViNjY0NDJjYTE0ZWJkYWMwY2U2MzE1ZiIsInVzZXJfaWQiOjJ9.GVx7EjthD-AI4j8Pqn684QxdPU3CYFK-Jh-_MYboUzA"}


###

GET http://127.0.0.1:8000/api/tulbur/274
Content-Type: application/json
Authorization: Bearer {{token}}

{}


###

POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Authorization: Bearer {{token}}

# {
#     "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNjU4MTYxMSwiaWF0IjoxNzI2NDk1MjExLCJqdGkiOiI5MTIyNzI3ZmMzYTA0YWQ5YWQ0YjRhMThiY2MzZWE2OSIsInVzZXJfaWQiOjF9.-E7fAROKKk9RaDC7x4R5kqcYg9qbmW2G_fFHdYGpOWI"
# }

