POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{"username":"admin", "password": "1"}

###

GET http://127.0.0.1:8000/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI2NDk3OTU5LCJpYXQiOjE3MjY0OTQzNTksImp0aSI6IjI2Y2U1ODUwN2NjZTQ2ZWQ5MTM2NDY2Zjg4ZjllYWRkIiwidXNlcl9pZCI6MX0.qfQX57oW0OWYrnNHEEZL9UMvnr1Sp5yN0oT5L8FTJBQ

{}

###

POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNjU3NjkwOCwiaWF0IjoxNzI2NDkwNTA4LCJqdGkiOiI2ZDczMjIzOGViNjY0NDJjYTE0ZWJkYWMwY2U2MzE1ZiIsInVzZXJfaWQiOjJ9.GVx7EjthD-AI4j8Pqn684QxdPU3CYFK-Jh-_MYboUzA"}


###

GET http://127.0.0.1:8000/api/tulbur/274
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI2NDk2Mjc0LCJpYXQiOjE3MjY0OTI2NzQsImp0aSI6IjZhOWYwM2Y5Yjk5MjRiOWY5MGYzMWVmOThmZmUwMzZhIiwidXNlcl9pZCI6MX0.x9lx4aYFsoSXutpYUYK-XmPpmnuQMtiZPsfRbCAZDmI

{}


###

POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI2NDk4ODExLCJpYXQiOjE3MjY0OTUyMTEsImp0aSI6IjYwY2ViOTZiMDY5NDQzMGVhMDU0YThhNjg4MWVkMDVkIiwidXNlcl9pZCI6MX0.68DteKHKFjez0OVRcr2W2Rj6PGacnut_t6dM297D7ik

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNjU4MTYxMSwiaWF0IjoxNzI2NDk1MjExLCJqdGkiOiI5MTIyNzI3ZmMzYTA0YWQ5YWQ0YjRhMThiY2MzZWE2OSIsInVzZXJfaWQiOjF9.-E7fAROKKk9RaDC7x4R5kqcYg9qbmW2G_fFHdYGpOWI"
}

