# Generated by Django 5.1.1 on 2024-09-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tulbur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=200)),
                ('is_calculated', models.CharField(max_length=200)),
                ('zone_id', models.CharField(max_length=200)),
                ('zone_type', models.CharField(max_length=200)),
                ('zone_no', models.CharField(max_length=200)),
                ('zone_name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('landuse_area', models.CharField(max_length=200)),
                ('zone_area', models.CharField(max_length=200)),
                ('base_fee_id', models.CharField(max_length=200)),
                ('resolution_id', models.CharField(max_length=200)),
                ('confidence_percent', models.CharField(max_length=200)),
                ('subsidized_area', models.CharField(max_length=200)),
                ('subsidized_fee_rate', models.CharField(max_length=200)),
                ('base_price_m2', models.CharField(max_length=200)),
                ('base_fee_per_m2', models.CharField(max_length=200)),
                ('landuses', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('payment', models.CharField(max_length=200)),
                ('sort_num', models.CharField(max_length=200)),
                ('error', models.CharField(max_length=200)),
            ],
        ),
    ]
