# Generated by Django 5.1.1 on 2024-09-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulbur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tulbur',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='base_fee_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='base_fee_per_m2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='base_price_m2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='confidence_percent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='error',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='gid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='is_calculated',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='landuse_area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='landuses',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='payment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='resolution_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='sort_num',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='subsidized_area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='subsidized_fee_rate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='zone_area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='zone_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='zone_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='zone_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tulbur',
            name='zone_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
